export const CHANGE_ARTIST = 'singerInfo/CHANGE_ARTIST'
export const CHANGE_SONGS_OF_ARTIST = 'singerInfo/CHANGE_SONGS_OF_ARTIST'
export const CHANGE_ENTER_LOADING = 'singerInfo/CHNAGE_ENTER_LOADING'
